## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux

julia:
  - 1.0
  - 1.3
  - 1.4
  - nightly

notifications:
  email: false

script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia --optimize=0 --project -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)';

jobs:
  allow_failures:
    - julia: nightly
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
