name = "Buffers"
uuid = "f06dc053-dc01-43d6-9774-6ac660c29876"
authors = ["Seth Axen <seth.axen@gmail.com>"]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
ZygoteRules = "700de1a5-db45-46bc-99cf-38207098b444"

[compat]
MacroTools = "0.5"
ZygoteRules = "0.2"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
